# Generated by Django 5.0 on 2023-12-17 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnetoOneApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='brain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='human', to='OnetoOneApp.brain'),
        ),
    ]
